/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.dialogs {
    export class OverGameDialogUI extends Dialog {
		public bg:Laya.Panel;
		public restartBtn:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("dialogs/OverGameDialog");
        }
    }
    REG("ui.dialogs.OverGameDialogUI",OverGameDialogUI);
}
export module ui.scenes {
    export class MainSceneUI extends Scene {
		public bg:Laya.Sprite;
		public contentBox:Laya.Box;
		public lineArea:Laya.Sprite;
		public bottleImg:Laya.Image;
		public touchArea:Laya.Sprite;
		public propBox:Laya.Box;
		public propBg:Laya.Sprite;
		public nextBox:Laya.Box;
		public nextImg:Laya.Image;
		public scoreSpr:Laya.Image;
		public crown:Laya.Sprite;
		public scoreBox:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scenes/MainScene");
        }
    }
    REG("ui.scenes.MainSceneUI",MainSceneUI);
}