export const EventDef = {
    CREATE_FRUITE: 'CREATE_FRUITE',
    MARK_IN_BOTTLE: 'MARK_IN_BOTTLE',
    REMOVE_FROM_BOTTLE: 'REMOVE_FROM_BOTTLE',
    RELEASE_CONTROLING_OBJ: 'RELEASE_CONTROLING_OBJ',
    ADD_BLOOM_ANI: 'ADD_BLOOM_ANI',
    ADD_SCORE: 'ADD_SCORE',
    SET_NEXT_FUITE: 'SET_NEXT_FUITE',
    OVER_GAME: 'OVER_GAME',
    RESET_GAME: 'RESET_GAME',
    REFRESH_PROP_BOX_UI: 'REFRESH_PROP_BOX_UI'
}